//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deathnote
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<int> DeathType { get; set; }
        public Nullable<System.DateTime> DayOfDeath { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Reason { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
