//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
