//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesDetail
    {
        public long Id { get; set; }
        public Nullable<long> MessagesId { get; set; }
        public Nullable<long> SenderId { get; set; }
        public string TextMessage { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Message Message { get; set; }

        public string Name { get; set; }
        public string AvatarUrl { get; set; }
        public string TimeSend { get; set; }
    }
}
