//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<long> FormId { get; set; }
        public Nullable<long> ToId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Desccription { get; set; }
        public Nullable<bool> isRead { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
