//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string AvatarURL { get; set; }
        public string About { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> CurrentCountryId { get; set; }
        public Nullable<int> CurrentCityId { get; set; }
        public Nullable<int> MotherTongueId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> CasteId { get; set; }
        public string SocialNetworkURL { get; set; }
        public string WebsiteURL { get; set; }
    
        public virtual Account Account { get; set; }
        #region Other
        public string MotherTongue { get; set; }
        public string CurrentCity { get; set; }
        public string Country { get; set; }
        public string Religion { get; set; }
        public int Point { get; set; }
        public int isFriend { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string VipType { get; set; }
        #endregion
    }
}
