//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLTT.WIILOVE.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WiiloveEntities : DbContext
    {
        public WiiloveEntities()
            : base("name=WiiloveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Deathnote> Deathnotes { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessagesDetail> MessagesDetails { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProfileTracking> ProfileTrackings { get; set; }
        public virtual DbSet<SystemParameter> SystemParameters { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserOnline> UserOnlines { get; set; }
        public virtual DbSet<UserRanking> UserRankings { get; set; }
        public virtual DbSet<UserRelationship> UserRelationships { get; set; }
    }
}
